Update CI and doc github action to built documentation using mdbook and mdbook-katex wget binaries

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,6 +4,7 @@ on:
     branches: ["main"]
   pull_request:
     branches: ["main"]
+
 jobs:
   build-and-test:
     runs-on: ubuntu-latest
@@ -15,11 +16,13 @@ jobs:
       - name: Install Dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install -y build-essential cmake gnuplot \
+          sudo apt-get install -y \
+            build-essential cmake gnuplot \
             libjpeg-dev libpng-dev libfreetype6-dev libfontconfig1-dev \
-            libqhull-dev zlib1g-dev
-            # TODO: Add libx11-dev/OpenGL/Qt/X11 packages
-            # libxt6 libxrender1 libxext6 libglx-mesa0 libqt6widgets6 qtbase5-dev
+            libqhull-dev zlib1g-dev \
+            libx11-dev libxt-dev libxrender-dev libxext-dev \
+            libgl1-mesa-dev libglu1-mesa-dev libglfw3-dev \
+            libxt6 libxrender1 libxext6 libglx-mesa0 libqt6widgets6 qtbase5-dev
 
       - name: Get GR submodule commit
         id: gr-sha
@@ -36,6 +39,9 @@ jobs:
         if: steps.gr-cache.outputs.cache-hit != 'true'
         run: |
           cmake -S third_party/gr -B third_party/gr/build \
+            -Wno-dev \
+            -DCMAKE_C_FLAGS="-w" \
+            -DCMAKE_CXX_FLAGS="-w" \
             -DGR_INSTALL=ON \
             -DCMAKE_INSTALL_PREFIX=$(pwd)/third_party/gr/install \
             -DCMAKE_DISABLE_FIND_PACKAGE_Qt6=ON \
@@ -44,10 +50,25 @@ jobs:
           cmake --build third_party/gr/build --parallel
           cmake --install third_party/gr/build
 
-      - name: Verify GR install
+      - name: Verify GR install and plugins
+        # run: |
+        #   ls third_party/gr/install/lib/libGR.so
+        #   ls third_party/gr/install/include/gr.h
+        #   # X11 and OpenGL/GR3 plugins
+        #   ls third_party/gr/install/lib/libGR3.so
+        #   ls third_party/gr/install/lib/x11plugin.so
         run: |
-          ls third_party/gr/install/lib/libGR.so
-          ls third_party/gr/install/include/gr.h
+          for file in \
+            third_party/gr/install/lib/libGR.so \
+            third_party/gr/install/include/gr.h \
+            third_party/gr/install/lib/libGR3.so \
+            third_party/gr/install/lib/x11plugin.so; do
+            if [ -f "$file" ]; then
+              echo " OK: $file"
+            else
+              echo " ERROR: $file missing!" && exit 1
+            fi
+          done
 
       - name: Build All
         run: make all PLOT_BACKEND=GR
